### ISSUE TITLE
Est-ce que l'identifier obligatoire de la ressource Location n'est pas trop contraignante ?

### ISSUE THREAD

**Issue by nriss** [Interop-Sante/hl7.fhir.fr.core#100]
https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/594921ed9a96efa5c123be1d22d552a0cf787717/input/fsh/profiles/FRCoreLocationProfile.fsh#L19

**Comment by nriss** [comment]
Discussion : 
Etonnant qu'il n'y ait pas d'identifiant métier de Location (lieu sans identifiant) dans le ROR. Comment est-ce possible de gérer ces localisations sans identifiant métier ?
Les identifiants techniques ne sont pas pérennes dans le temps donc ne sont pas satisfaisant pour identifier un lieu.

**Comment by nriss** [comment]
Préciser "Mauvaise pratique d'utiliser uniquement l'identifiant technique et ne pas avoir d'identifiant métier"

**Comment by sdemeyANS** [comment]
cf issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/196 IG ROR
