### ISSUE TITLE
Identifier Slices : binding ValueSet

### ISSUE THREAD

**Issue by GCHASTIN** [Interop-Sante/hl7.fhir.fr.core#113]
Pour le profil FR CORE Patient Profile, pour les slices de l'identifier, pourquoi ne pas indiquer les binding des ValueSets sur les type?
Seul l'élément type de la slice NDP indique le ValueSet à utiliser.

J'ai également remarqué que les ValueSets, lorsqu'ils sont indiqués dans les profils, sont cliquable. Ce n'est pas le cas des CodeSystem propres à FrCore (du moins pour fr-core-v2-0203) .

Exemple :
Lorsque le system https://hl7.fr/ig/fhir/core/CodeSystem/fr-core-v2-0203 est indiqué on ne peut pas l'atteindre par un lien et consulté les valeurs de ce dernier.

**Comment by nriss** [comment]
Hello Georges Alexandre ! 

Peux-tu me mettre une capture d'écran du lien non cliquable ? Je vois juste les fixedValue qui ne sont pas cliquable mais c'est normal, c'est que lorsqu'il y a un binding que c'est cliquable


Je suggère :

- [ ] Supprimer le binding de la slice NDP (ne sert à rien car la valeur est fixée)
- [ ] Mettre un binding vers le ValueSet dans la slice par défaut Patient.identifier.type, j'en ai parlé ici : https://github.com/Interop-Sante/hl7.fhir.fr.core/issues/91

**Comment by GCHASTIN** [comment]
Salut Nicolas, 

Merci pour ta réponse, je suis ok avec toi.

Voici la capture d'écran : 
![2024-01-19_18h08_47](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/140815492/28d63929-fd4f-446e-8278-0b013545f7e7)

Effectivement je trouve que c'est bien de rajouter le binding vers le ValueSet je n'avais pas vu l'issue #91.

Sorry :)

**Comment by nriss** [comment]
C'est effectivement normal que ce soit pas cliquable, c'est le générateur d'IG qui est développé comme ça :)
Cf us-qui a le même comportement:

![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/48218773/e86313c2-e6ca-4e49-837a-d46ffeb614ec)
https://hl7.org/fhir/us/core/STU5/StructureDefinition-us-core-bmi.html

Je clos l'issue, les tâches étant renseignées en https://github.com/Interop-Sante/hl7.fhir.fr.core/issues/91
