### ISSUE TITLE
fr-organization-type "unité d'activité"

### ISSUE THREAD

**Issue by paulineheurtebise** [Interop-Sante/hl7.fhir.fr.core#120]
Bonjour, 
Dans le VS [fr-organization-type](https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783673), que représente la valeur  "unité d'activité" ? 
Pourrait - elle être rapprochée de la notion d' "unité élémentaire" du [JDV_J203-TypeOrganisationInterne-ROR](https://mos.esante.gouv.fr/NOS/JDV_J203-TypeOrganisationInterne-ROR/JDV_J203-TypeOrganisationInterne-ROR.pdf) ? 
Merci.

**Comment by nriss** [comment]
Unité d'activité : CAC (=UAC) dans le système hospitalier, axe d'analyse financière.

Peux-tu définir à quoi correspond l'unité élémentaire  ?
https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/ValueSet-fr-core-core-organization-type.html
Il faudra possiblement aligner le MOS avec les profils FrCore

Sera à réétudier avec le GT de @flrt

**Comment by isa-ans** [comment]
Organisation des soins et fonctionnement médical : https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072665/LEGISCTA000006171469/2000-06-22
   "Les services et les départements sont placés sous la responsabilité d'un médecin, biologiste, odontologiste ou pharmacien hospitalier.
   **Les unités fonctionnelles sont les structures élémentaires de prise en charge des malades par une équipe soignante ou médico-technique, identifiées par leurs fonctions et leur organisation** ainsi que les structures médico-techniques qui leur sont associées.
   Les services sont constitués d'unités fonctionnelles de même discipline.
   Les départements sont constitués d'au moins trois unités fonctionnelles.
   A titre exceptionnel, lorsqu'une unité fonctionnelle ne présente pas de complémentarité directe avec d'autres unités de même discipline ou qu'il n'existe pas d'unité ayant la même activité, elle peut constituer un service."

l'unité élémentaire n'a pas de définition officielle. Il s'agit en fait d'UF

**Comment by nriss** [comment]
Merci @isa-ans, que pensez-vous de clore l'issue dans ce cas ? J'ai l'impression que l'UE n'a pas sa place dans FrCore compte tenu de ce qui a été dit

**Comment by isa-ans** [comment]
Si le ROR se base sur les profils FHIR -Fr ils ne trouveront pas la notion d'UE dans FrCore.

**Comment by nriss** [comment]
@paulineheurtebise peut-on cloturer l'issue ?

**Comment by paulineheurtebise** [comment]
Merci des précision apportée, je clos
