### ISSUE TITLE
Ajouter une slice "Numéro de sécurité sociale" dans le profil FrPatient

### ISSUE THREAD

**Issue by alexgrosbois** [Interop-Sante/hl7.fhir.fr.core#128]
Bonjour,

Je viens de remarquer qu'il n'y a pas de slice définie pour le Numéro de Sécurité Sociale (N°SS - utilisé pour les remboursements).
Celui ci peut différer de l'INS, essentiellement dans le cas des enfants assurés avec le NSS de leur parent.

![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/133106181/3427ee45-7fb3-470a-9c77-13b5740e63d6)

Il n'existe pas non plus de code associé au n° SS dans le FR Core ValueSet Patient identifier type.
Il me semble qu'il pourrait être utile de définir ce slice, mais il y a peut être des arguments contre.

**Comment by alexgrosbois** [comment]
Pour alimenter le débat, et puisque ce n°SS peut etre partagé par plusieurs individus au sein d'une famille par exemple, ce n'est peut etre pas judicieux de le traiter comme un identifier
Dans la doc de spécification, il est bien écrit que les identifier sont censés référencer un unique objet au sein d'un même système.

![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/133106181/908d44d1-f49a-4ead-b29d-cfefc7a5f1c0)

**Comment by ypoiron** [comment]
Il est important de ne pas confondre le NIR de facturation avec l’INS-NIR. Dans la documentation IHE PAM France, le NIR de facturation permet de faire transiter :
• Numéro de sécurité social de l’ayant droit ou du bénéfiaire (patient) : PID.3 avec un type (CX.5) = NH
• Numéro de sécurité social de l’ouvrant droit (assuré) : IN1.49 avec un type (CX.5) = SS

_Note : Dans le cas où le patient est l’assuré, les deux valeurs sont égales. Si le patient est un ayant droit, le champ IN1-49 contient le n° de sécurité sociale l’assurée et le champ PID.3, celui du bénéficiaire (s’il en dispose d’un)._

![Uploading Screen 2024-02-12 à 11.13.57.jpg…]()
