### ISSUE TITLE
Limitation sur le nombre de prénoms de naissance

### ISSUE THREAD

**Issue by abdelkrimb** [Interop-Sante/hl7.fhir.fr.core#131]
Bonjour,

https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/59376e89932767f5567b3cf8711e65d6bf7b6805/input/fsh/profiles/FRCorePatientProfile.fsh#L93

La contrainte appliquée sur le champs prénoms de naissance ( "official") ne permet pas de respecter l'exigence [Exi SI 04] du RNIV.
( page 11 https://esante.gouv.fr/sites/default/files/media_entity/documents/RNIV%201%20Principes%20communs_1.pdf)

![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/8101226/d426ad36-9cde-477c-8f7d-00109a6b405c)

Quand je valide ma ressource qui ressemble à ça:
![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/8101226/2684ea2e-eeb2-4e82-b261-be5f8be7b4d1)

j'obtiens une erreur ("diagnostics": "Patient.name:officialName.given: max allowed = 1, but found 2). 
![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/8101226/ca568d75-7347-42db-9e78-76fa18345cc1)

Est ce qu'il y a une explication à cette contrainte ?

Merci
Karim

**Comment by nriss** [comment]
Hello, merci pour ton issue!

Je pense que c'est un relicat d'une contrainte INS ou il faut y avoir la liste des prénoms au format texte. Ca me paraît cohérent de relaxer cette contrainte.

Dans le cadre du patient INS, on a déplacé cet attribut de Patient.name.given à name[officialName].extension[birth-list-given-name], donc je ne vois pas de soucis pour relaxer

**Comment by nriss** [comment]
Dans le cadre de l'INS, le premier prénom est un trait permettant d'identifier la personne, c'est la raison pour laquelle on avait mis 1..1 .

Il se pose la question : est-ce que le nom INS est le même que le nom officiel ?

Solutions envisagées : 
- Créer une extension complexe contenant : la liste des prénoms et le premier prénom

- (piste privilégiée) Le patient INS ne représente pas forcément une identité qualifiée :
1/ On relâche la contrainte Patient.name.given et Patient.name.family dans FrCorePatient que l'on reporte dans FrCorePatientINS
2/ On relâche la contrainte "* extension[identityReliability].extension[identityStatus].valueCoding = https://hl7.fr/ig/fhir/core/CodeSystem/fr-core-cs-fiabilite-identite#VALI" pour que le FrCorePatientINS soit un patient ins qualifié + autres status
3/ On rajoute un invariant : si identité est VALI, on doit avoir un identifier[INS-NIR] ou identifier[INS-NIA]

**Comment by abdelkrimb** [comment]
Je te remercie pour tes retours et tes explications Nicolas.

L'option 2 me semble optimale. 
J'aime bien l'idée de distinguer le FrCorePatientINS (utilisée dans le contexte du service INSi)  et celui du FrCorePatient ( pour transporter les identités dans le cas générale).

**Comment by nriss** [comment]
C’est l’option choisie dans la PR #133 🙂
