### ISSUE TITLE
slice identifier organization

### ISSUE THREAD

**Issue by sdemeyANS** [Interop-Sante/hl7.fhir.fr.core#151]
Bonjour,

Pour le ROR, la slice identifier sur organization permet de distinguer le numéro SIREN et le numéro SIRET:
https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-organization.html

Est-ce possible de faire évoluer le profil fr-core-organization dans ce sens?

**Comment by nriss** [comment]
Hello, il va également falloir changer les types qui contiennent les anciennes URLs :
![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/48218773/448d51cb-e8cd-4d2e-af54-de08bddf9915)

**Comment by sdemeyANS** [comment]
dans le ROR il y a aussi identifierOI

**Comment by flachalESEA** [comment]
> dans le ROR il y a aussi identifierOI mais certainement spécifique au cas d'usage

Bonjour, 

La modélisation d'une organisation interne est utile dans le cas des cercles de soins, où les membres des cercles de soins sont plutôt des services que des EG entiers. On a besoin de cette granularité et donc de cette slice côté organization.identifier. Il faudrait idéalement que le system de la slice soit pas forcément celui du ROR.

**Comment by nriss** [comment]
Cf ce qui a été fait sur le CDS : https://github.com/ansforge/IG-fhir-cercle-de-soins/blob/ft-3-add-narative/input/fsh/profiles/CDS_Organization.fsh

**Comment by nriss** [comment]
Discussion du 13 mai : ok pour mettre les deux slices SIREN / SIRET. A rediscuter dans le GT Structure
