### ISSUE TITLE
Observation Resource - Merge all in one single Observation ? 

### ISSUE THREAD

**Issue by arribbar** [Interop-Sante/hl7.fhir.fr.core#157]
Could it be possible to merge all pages concerning Observation Resource in a single one ? 
Like this, it would be easier to find the info we are looking for. Working on HL7, we are used to only one resource to deal with and now, a bit lost with all different possibilities ^^

And maybe have some different examples

Now, we have:
- [Observation Bmi](https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-observation-bmi.html)
- [Observation Body Height](https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-observation-body-height.html)
- [Observation Blood Pressure](https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-observation-bp.html)
- [Observation Respiratory Rate](https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-observation-resp-rate.html)
- [Observation Body Weight](https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-observation-body-weight.html)
- [Observation Head Circum](https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-observation-head-circum.html)
- [Observation Heart Rate](https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-observation-heartrate.html)
- [Observation Saturation Oxygen](https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-observation-saturation-oxygen.html)

**Comment by nriss** [comment]
Have you got an example of what you are waiting for ? Something like that ? https://ansforge.github.io/IG-fhir-mesures-de-sante/ig/main/Terminologies.html

**Comment by nriss** [comment]
We categorized the list of profiles there : https://hl7.fr/ig/fhir/core/profile_list.html
