### ISSUE TITLE
Resource : "FR Core Patient INS Profile" [Ajout des autorités d'affectation de tests et démo]  

### ISSUE THREAD

**Issue by M-Priour** [Interop-Sante/hl7.fhir.fr.core#162]
Dans la version actuelle du profil, il n'est pas possible de passer un patient test sur les autorités d'affectation de tests : 
- 1.2.250.1.213.1.4.10 : Autorité d’affectation des INS-NIR de test
- 1.2.250.1.213.1.4.11 :  Autorité d’affectation des INS-NIR de démonstration

Pour faire des tests de bout en bout avec appel au téléservice, il serait sans doute intéressant de rajouter ces autorités d'affectation.

**Comment by nriss** [comment]
Décision du 13 mai : ok pour rajouter les 2 slices dans FrCorePatient INS
