### ISSUE TITLE
StructureDefinition-patient-birthPlace

### ISSUE THREAD

**Issue by GCHASTIN** [Interop-Sante/hl7.fhir.fr.core#191]
Lorsque je télécharge le package je ne trouve pas la StuctureDefinition correspondant à l'extension patient-birthPlace. Est ce que cela vient du fait qu'elle ne soit pas spécifique à FrCORE?

**Comment by nriss** [comment]
Effectivement! C'est une extension qui vient du extension-pack d'HL7 international!
Cf url canonique qui commence par hl7.org 

<img width="986" alt="image" src="https://github.com/user-attachments/assets/85a53214-9af2-492d-940f-22ac76929d03">
--> https://hl7.org/fhir/extensions/5.1.0/StructureDefinition-patient-birthPlace.html

La StructureDef est associée au package FrCore via ses dépendances (hl7.fhir.uv.extensions.r4#5.1.0)

<br class="Apple-interchange-newline">[hl7.fhir.uv.extensions.r4#5.1.0](https://simplifier.net/packages/hl7.fhir.uv.extensions.r4/5.1.0)
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/1e757192-b539-43e6-9d8f-d924fa52348e">
