### ISSUE TITLE
Link for Patient example broken

### ISSUE THREAD

**Issue by cdelanchy** [Interop-Sante/hl7.fhir.fr.core#192]
# Description du problème | Description of the issue

Un lien existe dans les profils FrPatient et FrPatientINS mais le lien pointe vers une 404.

# Fichier•s concerné•s | Concerned files

# Solution proposée | Proposed resolution

Réparer le lien pour emmener vers l'exemple de Patient

**Comment by nriss** [comment]
Je ne comprends pas, le lien n'est pas bon 

https://hl7.fr/ig/fhir/core/Patient-ExampleFRCorePatient001.html
https://hl7.fr/ig/fhir/core/Patient-ExamplefrCorePatient001.html

**Comment by nriss** [comment]
Compris, l'erreur sera corrigée à la prochaine publication de l'IG :)

**Comment by cdelanchy** [comment]
Désolé, j'ai ouvert le ticket pendant que je donnais un cours. C'était plus en pense-bête ! Effectivement, le lien qui est mis dans l'IG disponible en ligne (https://hl7.fr/ig/fhir/core/StructureDefinition-fr-core-patient-ins.html) mène à une 404.

Le lien est celui-ci : https://hl7.fr/ig/fhir/core/Patient-ExampleFRCorePatient001.html

**Comment by nriss** [comment]
Effectivement, la casse a changé et n'a pas été mise à jour sur le site web! En mettant "fr" en minuscule, le problème est résolu!
J'ai fait le correctif, ça sera réglé rapidement :)

Merci pour l'issue! Et désolé pour la 404 pendant le cours :)

**Comment by ypoiron** [comment]
Hello, c'est réglé normalement ! :)

**Comment by cdelanchy** [comment]
Merci beaucoup, @ypoiron et @nriss ! Effectivement, c'est réglé :)

Et pas de problème pour le cours, nous sommes allés voir directement dans le repo GitHub du coup ;)
