### ISSUE TITLE
Uniformiser id, name & url

### ISSUE THREAD

**Issue by nriss** [Interop-Sante/hl7.fhir.fr.core#2]
name : utiliser le format upper camel case. Ex : FrPatient

id : utiliser le format kebab-case, ex : fr-patient

url : [base]/StructureDefinition/[id]

Un projet d'uniformisation sera lancé en 2023 avec la transformation de FrCore en IG avec FSH

https://github.com/ansforge/FIG_ans-ig-sample/wiki/D%C3%A9veloppement-d'un-nouvel-IG

**Comment by ypoiron** [comment]
Done merge main
