### ISSUE TITLE
Extension FR Core Nationality Profile

### ISSUE THREAD

**Issue by isa-ans** [Interop-Sante/hl7.fhir.fr.core#20]
l'extension est basée sur l'extension internationale patient-nationality mais il n'y a pas de binding définit sur le code de l'extension (codeableConcept permettant de définir la nationalité du patient)

**Comment by ypoiron** [comment]
Cette extension n'est pas utilisée, en draft, devons-nous la supprimer ?

**Comment by ypoiron** [comment]
JDV manquant + URL canonique du FrPatient

**Comment by nriss** [comment]
- URL canonique de l'extension à adapter à fr core
https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783697/~overview

- Trouver un JDV pour les nationalités et mettre en place un binding

**Comment by ypoiron** [comment]
https://mos.esante.gouv.fr/NOS/TRE_R268-PaysProvenanceISO/FHIR/TRE-R268-PaysProvenanceISO/TRE_R268-PaysProvenanceISO-FHIR.json
