### ISSUE TITLE
Extension FR Core Patient Insi Birth Place Profile

### ISSUE THREAD

**Issue by isa-ans** [Interop-Sante/hl7.fhir.fr.core#21]
Cette extension permet de spécifier le code INSEE au niveau d'une adresse en provenance du TLS INSi. Pourquoi avoir créé cette extension alors que le profil FrCoreAddress contient en extension le code INSEE?
D'autre part, dans le profil FrCorePatient, l'extension birthPlace est de type Address (type de données FHIR qui n'utilise pas l'extension FR Core Patient Insi Birth Place Profile.

**Comment by ypoiron** [comment]
L'extension n'est pas utilisée, devons-nous la supprimer ? 

Même demande que la #3

**Comment by nriss** [comment]
Changer l'url de Patient.extension:birthplace par l'url de l'extension d'IS
Reprofiler FrBirthPlace : utiliser FrAddress et mettre les contraintes du discrict dans birthplace et non pas dans FrAddress
