### ISSUE TITLE
JDV FRCoreValueSetEncounterDischargeDisposition

### ISSUE THREAD

**Issue by isa-ans** [Interop-Sante/hl7.fhir.fr.core#24]
le JdV n'est pas complet

**Comment by ypoiron** [comment]
Il manque des valeurs ?

**Comment by nriss** [comment]
Peux-tu nous transmettre le Excel @isa-ans ?

**Comment by isa-ans** [comment]
> Peux-tu nous transmettre le Excel @isa-ans ?
> 
> [EDIT] C'est bon on a trouvé avec yohann

Ok, je ne sais pas si le JdV indiqué dans le tableau Excel est toujours d'actualité, mais à priori c'est le même que celui utilisé dans PAM-Fr

**Comment by nriss** [comment]
Faire la demande pour enrichir et aligner le MOS avec PAM et le JDV HL7
https://www.hl7.org/fhir/R4/valueset-patient-contactrelationship.html
