### ISSUE TITLE
Patient.extension:birthPlace

### ISSUE THREAD

**Issue by nriss** [Interop-Sante/hl7.fhir.fr.core#3]
L'Address est profilée directement dans FrPatient et non dans l'extension birthplace.

- Profiler l'extension birthPlace (https://www.hl7.org/fhir/extension-patient-birthplace.html) et appliquer FrAddress
- Ajouter le cog sur FrAddress en optionnel ?
- Binding sur le district conformément au ci-sis (https://esante.gouv.fr/sites/default/files/media_entity/documents/ans_cisis-tec_annexe-ins_1.5.pdf, page 6)

**Comment by Monstermanu** [comment]
Pour les communes existantes il existe https://public.opendatasoft.com/explore/dataset/correspondance-code-insee-code-postal/table/ qui permet de faire la correspondance entre code commune, code postal et nom de commune. Cependant, il me semble que ça ne couvre pas les anciennes communes ou les communes qui ont été fusionnées. 
Pour le cas des personnes nées en dehors de France, district correspond au code COG du pays de naissance. La table d'association https://mos.esante.gouv.fr/NOS/ASS_A25-PaysProvenanceISO-PaysProvenanceCOG permet de mapper ce code sur le code ISO des pays. La problématique est la même pour les pays qui ont disparu (ex. Tchécoslovaquie ou Yougoslavie).

**Comment by nriss** [comment]
Reprofiler https://www.hl7.org/fhir/extension-patient-birthplace.html pour contraindre à FrAddress ?
