### ISSUE TITLE
Profil FR Core Patient

### ISSUE THREAD

**Issue by isa-ans** [Interop-Sante/hl7.fhir.fr.core#30]
Je ne vois pas l'utilité de slicer l'élément name, cela complique les implémentations.
l'élément use du type de données FrHumanName permet de différencier le nom usuel du nom officiel sans avoir à introduire un slicing.

**Comment by nriss** [comment]
Permet de rendre obligatoire family et given dans le cas d'official name pour l'INS
A documenter dans l'IG
