### ISSUE TITLE
FR Core Schedule/Binding JdV sur schedule/identifier/type

### ISSUE THREAD

**Issue by isa-ans** [Interop-Sante/hl7.fhir.fr.core#33]
Le binding sur le type d'identifiant n'a pas de sens.

**Comment by nriss** [comment]
Tu veux dire dans identifier.use ?
Il n'y a pas de binding à dans identifier.type

<img width="796" alt="image" src="https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/48218773/f808d015-478c-4278-a620-7b70163792a7">

**Comment by nriss** [comment]
* identifier.use from IdentifierUse (required) supprimé (inutile)
