### ISSUE TITLE
Profil FrPractionerRoleExercice

### ISSUE THREAD

**Issue by isa-ans** [Interop-Sante/hl7.fhir.fr.core#34]
Le profil FrPractitionerRoleExercice est utilisé par le projet RASS. Faut-il le supprimer du package FR Core?

**Comment by nriss** [comment]
==> Réintégrer le profil au package car utilisé dans le package SAS

**Comment by nriss** [comment]
Typo practioner
<img width="191" alt="image" src="https://user-images.githubusercontent.com/48218773/220076893-2e646b8f-3c41-44a7-848f-7361d03c0d75.png">
