### ISSUE TITLE
ID non valide FHIR

### ISSUE THREAD

**Issue by wylem-bars** [Interop-Sante/hl7.fhir.fr.core#37]
Dans le profile FrOrganizationTotalNumberOfTheoricalAccomodationSpace, l'id n'est pas un ID valide FHIR.
https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/main/input/resources/StructureDefinition-fr-core-organization-total-number-of-theorical-accomodation-space.xml

**Comment by nriss** [comment]
Limite à 64 caractères https://www.hl7.org/fhir/datatypes.html#id

**Comment by nriss** [comment]
Sera corrigé dans l'IG
