### ISSUE TITLE
Binding d'un élément complexe sur un ValueSet

### ISSUE THREAD

**Issue by wylem-bars** [Interop-Sante/hl7.fhir.fr.core#38]
Certains éléments complexes sont bindés sur un ValueSet. Exemple : https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/main/input/resources/StructureDefinition-fr-core-service-type-duration.xml
`{
                "id": "Extension.extension:serviceType",
                "path": "Extension.extension",
                "sliceName": "serviceType",
                "short": "Type of the service that has to be performed during the appointment | Typedu service à assurer durant le RDV",
                "min": 1,
                "max": "1",
                "binding": {
                    "strength": "extensible",
                    "description": "This value set defines an example set of codes of service-types.",
                    "valueSet": "http://hl7.org/fhir/ValueSet/service-type"
                }
            }`

**Comment by nriss** [comment]
Corrigé avec le passage en IG
