### ISSUE TITLE
Nom de slice réutilisé

### ISSUE THREAD

**Issue by wylem-bars** [Interop-Sante/hl7.fhir.fr.core#39]
Certains noms de slice sont réutilisés dans plusieurs profiles, ce qui peut provoquer des conflits. EX : validationMode dans https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/main/input/resources/StructureDefinition-fr-core-identityreliability.xml et https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/main/input/resources/StructureDefinition-fr-core-patient.xml

**Comment by nriss** [comment]
Corrigé ici : https://github.com/Interop-Sante/hl7.fhir.fr.core/pull/57
