### ISSUE TITLE
Binding de type extensible override par un preferred

### ISSUE THREAD

**Issue by wylem-bars** [Interop-Sante/hl7.fhir.fr.core#40]
Peut aussi poser problème pour l'utilisation dans les IG par exemple. Ex : https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/main/input/resources/StructureDefinition-fr-core-patient.xml Patient.contact.relationship

**Comment by nriss** [comment]
Peux-tu préciser ta demande ?
