### ISSUE TITLE
Homogénéisation de l’échange des prénoms d’un patient

### ISSUE THREAD

**Issue by jccauvin** [Interop-Sante/hl7.fhir.fr.core#44]
Le volume 1 du RNIV (“Principes d’identification des usagers communs à tous les acteurs de santé”) précise page 32 comment le(s) prénom(s) de naissance doivent être saisi(s) dans les applications. La notion de 2ème, 3ème prénom disparait. La personne a un premier prénom de naissance et une liste de prénoms de naissance disponible sur “la ligne prénom du document d’identité” utilisé pour saisir l’identité d’une personne.
L’objectif de cette proposition d’évolution est de prendre en compte cette partie du RNIV dans le profil frPatient, tout en étant aligné avec les messages HL7 V2 (voir pièce jointe).

- La cardinalité de Patient.officialName.text doit être 1..1. En effet, text contient l'ensemble des prénoms, dont au moins given.
- La cardinalité de Patient.usualName.given et de Patient.usualName.text doivent être 1..1. 
- Reprendre les exemples de la ressource Patient.

[IHE-CP-ITI-FR-2023-nnn_GivenNames_v1.docx](https://github.com/Interop-Sante/hl7.fhir.fr.core/files/10815480/IHE-CP-ITI-FR-2023-nnn_GivenNames_v1.docx)
[ExemplesCorrigés.zip](https://github.com/Interop-Sante/hl7.fhir.fr.core/files/10815771/ExemplesCorriges.zip)

**Comment by Ben0it-T** [comment]
Bonjour,
Est-il possible d'ajouter des exemples avec des prénoms composés. Cela permettrait de balayer différentes situations, à l'image de ce qui apparait dans le CP ?

Par exemple,
Ressource Patient dont le prénom de naissance est un prénom composé utilisant le séparateur espace
- Prénom de naissance : ANNE SOPHIE
- Second prénom : FRANCOISE
- Liste des prénoms de l'acte de naissance : ANNE SOPHIE FRANCOISE
```json
"name": [
    {
      "use": "official",
      "family": "X",
      "given": [
        "ANNE SOPHIE"
      ],
      "text": "ANNE SOPHIE FRANCOISE"
    }
],
```

```xml
<name>
    <use value="official" />
    <family value="X" />
    <text value="ANNE SOPHIE FRANCOISE" />
    <given value="ANNE SOPHIE" />
</name>
```

Ressource Patient dont le prénom de naissance est un prénom composé utilisant le séparateur `-`
- Prénom de naissance : ANNE-SOPHIE
- Second prénom : FRANCOISE
- Liste des prénoms de l'acte de naissance : ANNE SOPHIE FRANCOISE
```json
"name": [
    {
      "use": "official",
      "family": "X",
      "given": [
        "ANNE-SOPHIE"
      ],
      "text": "ANNE SOPHIE FRANCOISE"
    }
],
```

```xml
<name>
    <use value="official" />
    <family value="X" />
    <text value="ANNE SOPHIE FRANCOISE" />
    <given value="ANNE-SOPHIE" />
</name>
```

Ressource Patient dont le prénom de naissance est un prénom composé utilisant le séparateur `-`
- Prénom de naissance : ANNE-SOPHIE
- Second prénom : FRANCOISE
- Liste des prénoms de l'acte de naissance : ANNE-SOPHIE FRANCOISE
```json
"name": [
    {
      "use": "official",
      "family": "X",
      "given": [
        "ANNE-SOPHIE"
      ],
      "text": "ANNE-SOPHIE FRANCOISE"
    }
],
```

```xml
<name>
    <use value="official" />
    <family value="X" />
    <text value="ANNE-SOPHIE FRANCOISE" />
    <given value="ANNE-SOPHIE" />
</name>
```

**Comment by flrt** [comment]
le champ `text` doit contenir tous les éléments du nom donc 
```
<name>
    <use value="official" />
    <family value="X" />
    <text value="ANNE-SOPHIE FRANCOISE" />
    <given value="ANNE-SOPHIE" />
</name>
```
est incorrect

il faut 

```
<name>
    <use value="official" />
    <family value="X" />
    <text value="ANNE-SOPHIE FRANCOISE X" />
    <given value="ANNE-SOPHIE" />
    <given value="FRANCOISE" />
</name>
```

Il n'y a pas de champ adapté pour une liste de prénoms de naissance, telle que fournie par le téléservice INSi, une extension est nécessaire.

**Comment by flrt** [comment]
oui d'où :

- issue #45 : pour préciser (dans le profile) que c'est bien le 1er prénom que l'on doit avoir
- issue #46 : pour indiquer que ce qui est dans l'annexe du CI-SIS pour Patient.name.text n'est pas correct
