### ISSUE TITLE
utilisation de patient.name.text de type official

### ISSUE THREAD

**Issue by flrt** [Interop-Sante/hl7.fhir.fr.core#46]
Dans le document du CI-SIS https://esante.gouv.fr/sites/default/files/media_entity/documents/ans_cisis-tec_annexe-ins_1.5.pdf
l'utilisation du champ `text` est incorrecte.

Dans la spécification FHIR, Le champ `text` doit contenir toutes les parties du nom.

Si on conserve la contrainte de ne véhiculer qu'un seul prénom alors 

```
{
      "use": "official",
      "family": "DUPOND",
      "given": [
        "PIERRE"
      ],
      "text": "PIERRE ANTOINE JEREMIE"
}
```
est incorrect, il faut

```
{
      "use": "official",
      "family": "DUPOND",
      "given": [
        "PIERRE"
      ],
      "text": "PIERRE DUPOND"
}
```
Pour véhiculer la liste des prénoms retournées par le téléservice INSi, en appliquant une contrainte de non modification (diffusion sous la forme retournée, c'est-à-dire une liste de prénoms séparés par des espaces), il est nécessaire d'avoir une extension.

**Comment by ypoiron** [comment]
Bonjour Frédéric, c'est effectivement un choix qui avait été fait à l'époque. L'idée serait donc : 

1. Ajouter une extension pour la liste des prénoms retournés par le téléservice 
2. Supprimer la contrainte et la description sur le champ `text` 

Sommes-nous en phase ?

**Comment by flrt** [comment]
oui c'est tout à fait ça.

**Comment by nriss** [comment]
Après discussion, nous allons créer un profil FrPatientINS où nous allons notamment ajouter une extension listant les prénoms, il faudra également faire un CP sur l'annexe INS
