### ISSUE TITLE
Les system de Patient.identifier:PI/RRI.type ne sont pas corrects

### ISSUE THREAD

**Issue by nriss** [Interop-Sante/hl7.fhir.fr.core#49]
Les system sont actuellement : http://interopsante.org/CodeSystem/fr-core-v2-0203
Sauf que ceux-ci ne contiennent pas les codes PI - RRI

Il aurait fallu utiliser le CS http://terminology.hl7.org/CodeSystem/v2-0203

**Comment by GCHASTIN** [comment]
Inclure au valueSet http://interopsante.org/fhir/ValueSet/fr-core-patient-identifier-type le system http://interopsante.org/fhir/ValueSet/fr-core-patient-identifier-type (remplace http://interopsante.org/fhir/CodeSystem/fr-v2-0203)
