### ISSUE TITLE
Invalid file name in NPM package for fr-core-practitioner-role-exercice profile

### ISSUE THREAD

**Issue by zrsmith92** [Interop-Sante/hl7.fhir.fr.core#51]
Greetings! It looks like the [`fr-core-practitioner-role-exercice` profile](https://simplifier.net/frenchprofiledfhirar/frcorepractitionerroleexercice) is exported in the NPM package as `fr-practitioner--role-exercice..json` (notice the extra `.` before the extension).

This is causing problems when trying to import the package with [HAPI FHIR](https://hapifhir.io/)'s built-in `NpmPackageValidationSupport` (exception being thrown [here](https://github.com/hapifhir/org.hl7.fhir.core/blob/63e090a2d9896f008b525455871fb648229a19a0/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/npm/NpmPackage.java#L535-L537)).

Would it be possible to update the package to remove the extra period in the file name? Thanks!

**Comment by zrsmith92** [comment]
Additionally, I'm seeing a lot of inconsistencies in the canonical URL claims for various profiles between what is published on the simplifier [project](https://simplifier.net/frenchprofiledfhirar) and what is published in the [NPM package](https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0).

For example, the patient profile as listed in the [project](https://simplifier.net/frenchprofiledfhirar/frcorepatientprofile) should have the canonical URL `http://interopsante.org/fhir/StructureDefinition/fr-core-patient`.

However, in the [NPM Package](https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783568), it is `http://interopsante.org/fhir/StructureDefinition/FrPatient`

**Comment by nriss** [comment]
Thanks for your feedbacks !
We are working on publishing an IG, these problems will be resolved end 2023
