### ISSUE TITLE
Réparer la référence FrObservationHeartrate.performance (mauvaise url du profil FrPractitionerRole)

### ISSUE THREAD

**Issue by nriss** [Interop-Sante/hl7.fhir.fr.core#7]
Erreur remontée par Nicolas Arnoux sur le profil https://simplifier.net/frenchprofiledfhirar/FrObservationHeartrate

Remplacer l'url canonique du profil http://www.interopsante.org/fhir/structuredefinition/fr-practitioner-role.
Prendre les mêmes profils que pour FrObservationBMI :  https://simplifier.net/frenchprofiledfhirar/frobservationbmi

Package : https://simplifier.net/packages/ans.annuaire.fhir.r4/0.2.0

Travail à effectuer en parallèle de l'issue #1

**Comment by ypoiron** [comment]
@nriss je suis embêté je n'ai pas le practitioner-role

**Comment by nriss** [comment]
Mince .. Effectivement, ils référencent les PractitionerRole qui vont être supprimés (issue #1 )..

Je vois deux possibilités:
- Mettre une référence vers la ressource PractitionerRole de base
- Mettre une référence vers les profils annuaire

**Comment by ypoiron** [comment]
Ce sera plutôt vers le PractitionerRole de base

**Comment by nriss** [comment]
> * Mettre une référence vers la ressource PractitionerRole de base

Je suis plutôt d'accord oui!

**Comment by ypoiron** [comment]
Fixed #1
