### ISSUE TITLE
Supprimer la valeur other de Patient.Gender pour le patient INS

### ISSUE THREAD

**Issue by nriss** [Interop-Sante/hl7.fhir.fr.core#71]
Le ValueSet ne doit que contenir "male", "female", "unknown"

**Comment by mbrulliard** [comment]
Obejctif = cohérence CDA/FHIR - l’élément « administratriveGenderCode » de l’entête CDA utilise le JDV_J143-AdministrativeGender-CI-SIS (1.2.250.1.213.1.1.5.590) avec les 3 valeurs (F, M, UN)
