### ISSUE TITLE
Aligner l'annuaire santé et FrCore : fusion des PractitionerRole ?

### ISSUE THREAD

**Issue by nriss** [Interop-Sante/hl7.fhir.fr.core#82]
# Problématique

La communauté a révélé des commentaires sur la modélisation côté ANS : nous avons rajouté des extensions au profil PractitionerRole qui correspond à la civilité, au nom et au prénom sous lesquel exerce le professionnel (données renseignées par le PS lors de son inscription à l'ordre).
Cela semblait étrange aux consommateurs, car le Practitioner.name était parfois vide (car il s'agit d'une donnée restreinte).
Cf : https://github.com/ansforge/IG-fhir-annuaire/issues/21

D'autre part, l'ancien package annuaire (disponible sur simplifier) était complexe avec une chaîne de deux PractitionerRole (un correspondant à la Situation d'Exercice, et l'autre correspond à l'Exercice Professionnel du MOS.

# Situation actuelle

**Annuaire**

Annuaire a plusieurs packages : 
1/ le package utilisé dans les volets CI-SIS (avec l'extension partOf)
2/ les profils des nouveaux services de l'Annuaire (pas de partOf mais pas non plus de ressource Person), 
3/ les profils en cours d'élaboration (pas de partOf, un profil Person, plusieurs Practitioner par Person).

Ci-dessous, nous considérerons le cas 3

- Person (héritage Person) : cette ressource correspond à l'identité civile du praticien
- Practitioner (héritage FrPractitioner) : cette ressource correspond à l'exercice professionnel du praticien (ex : médecin, pharmacien...). Une Person peut avoir plusieurs ressources Practitioner associée si celle-ci est pharmacienne et médecin en même temps.
- PractitionerRole (héritage FrPractitionerRoleExercice) : cette ressource correspond à une situation d'exercice. Par exemple, un médecin peut exercer à la fois en libéral et à l'hôpital.

En résumé, une Person peut avoir plusieurs Practitioner associé.
un Practitioner peut avoir plusieurs rôles associés

**FrCore**

Pour Fr-Core, les 2 PractitionerRole définis reprennent les concepts du MOS mais ne sont pas conformes (lien direct des 2 PractitionerRole avec Practitioner mais pas de lien entre les PractitionerRole) :

- Practitioner : correspondant à la personne civile
- PractitionerRoleExerciceProfessionnel : correspondant à un exercice professionnel donné
- PractitionerRoleSituationExercice : correspond à une situation d'exercice dans un établissement donné.

Pour une description plus précise des contexte, Cf le MOS : https://mos.esante.gouv.fr/2.html#_9d79ff39-6b00-4aa6-ac03-7afb4a8aad2b

# La suite
Pour la première release au format IG,, nous allons laisser FrCore tel quel avec les deux profils PractitionerRole.
Nous allons en parallèle publier l'Annuaire avec l'héritage de FrCore tel que l'on a fait actuellement.

En parallèle, nous allons faire un appel à contribution pour recueillir l'avis des éditeurs : **y a-t-il vraiment des utilisateurs des 2 profils FrPractitionerRole qui justifient de les garder ?**

PR associée : https://github.com/Interop-Sante/hl7.fhir.fr.core/pull/61

Côté FrCore, les objectifs seraient de:
- [ ] Créer un profil FrPerson (à discuter)
- [ ] Supprimer le profil PractitionerRoleSituationExercice
- [ ] Renommer le profil PractitionerRoleExerciceProfessionel en FrPractitionerRole

Cela permettrait également de simplifier la compréhension de l'écosystème FHIR Fr

Issue liée : https://github.com/Interop-Sante/hl7.fhir.fr.core/issues/47

**Comment by mbrulliard** [comment]
Quelques commentaires (revue avec Pauline en bonus) : 
Partie Problématique : 
> La communauté a révélé des erreurs de modélisation:

La modélisation n'est pas fausse ! Peut être indiquer que la modélisation apporte des contraintes et qu'il y a des retours des éditeurs sur ces contraintes.

> Côté ANS, nous avons rajouté un name au profil PractitionerRole via une extension qui correspond au nom d'inscription d'un practicien hospitalier

Il s'agit de l'extension créée par l'Annuaire au niveau de PractitionerRole et qui porte la civilité, le nom et le prénom sous lesquels exerce le professionnel (donc le côté hospitalier est un peu restrictif)
Donc aujourd'hui practitioner.name = nom d'usage + nom d'état civil et practitionerRole.As-ext-practitionerrole-name = nom d'exercice - donc le name du practitioner peut être vide alors que le name du practitionerRole est renseigné (ok avec ça ! et effectivement, l'usage de Person est plus pertinent)

Partie Situation actuelle : 
Le titre est ambigu puisque pour l'Annuaire il n'y a pas une situation actuelle mais plusieurs : 1. le package utilisé dans les volets CI-SIS (avec l'extension partOf), 2. les profils des nouveaux services de l'Annuaire (pas de partOf mais pas non plus de ressource Person), 3. les profils en cours d'élaboration (pas de partOf, un profil Person, plusieurs Practitioner par Person).
Pour Fr-Core, les 2 PractitionerRole définis ne sont pas conformes au MOS (lien direct des 2 PractitionerRole avec Practitioner mais pas de lien entre les PractitionerRole)

Partie La Suite : 
Y a-t-il vraiment des utilisateurs des 2 profils FrPractitionerRole qui justifient de les garder ?

> Nous allons en parallèle publier l'Annuaire avec l'héritage de FrCore tel que l'on a fait actuellement

C'est vraiment ce que l'on fait actuellement ? (c'était bien l'idée de créer un FrPractitionerRole à partir duquel décliner les profils Annuaire mais je ne crois pas que ce soit le cas aujourd'hui avec les 2 FrPractitionerRole, je veux bien une confirmation si c'est effectivement comme ça que ça se passe)

**Comment by nriss** [comment]
L'extension FR Core Practitioner Specialty Extension  (https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/StructureDefinition-fr-core-practitioner-specialty.html) n'est pas utilisée dans FrCorePractitioner

**Comment by sdemeyANS** [comment]
petite typo également
<img width="590" alt="image" src="https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/117643165/06f745d0-dd62-4bf9-90ac-1c4358640c84">

**Comment by nriss** [comment]
Corrigé ici : https://github.com/Interop-Sante/hl7.fhir.fr.core/pull/137
