### ISSUE TITLE
Cardinalité des slices identifier pour le FrPatient

### ISSUE THREAD

**Issue by alexgrosbois** [Interop-Sante/hl7.fhir.fr.core#91]
Bonjour,

Je voulais signaler ce que je pense être des incohérence dans la cardinalité des slices identifier pour le profile FrPatient:

- D’abord les slices INS-C, INS-NIR et INS-NIA acceptent une cardinalité 0..n. Ces identifiants nationaux sont pourtant censés être uniques, et je ne visualise pas de cas pour lesquels on pourrait avoir besoin de plusieurs occurrences de ces slices.

- Au contraire les slices sur les identifiants locaux tels que l’IPP, le NDP ou même les identifiants régionaux possèdent une cardinalité 0..1. Il n’est donc pas possible d’étendre ce profile en augmentant la cardinalité car ce nouveau profile serait moins restrictif que son parent.
Pour des modèles de données Patient au niveau GHT/GCS/Région, et il pourrait être très intéressant de renseigner autant de couples IPP/Structure dans le Slice PI qu’il y a d’établissement, ceci afin de pouvoir rechercher le patient peu importe l’IPP local considéré.

Est-ce que ces choix sont basés sur des réflexions fonctionnelles que je n’aurais pas envisagées ?

Alexandre

**Comment by alexgrosbois** [comment]
Bonjour,
 
Nous avons échangé avec Krim Boureche sur ce sujet, et abouti à de nouvelles propositions pour la gestion de ces Slices identifier:
 
- D'abord pour la Slice "PI", Krim fait remarquer à juste titre qu'elle correspond à un "Internal Patient Identifier". Dans ce sens il est logique que celle-ci ait une cardinalité maximale à 1 pour un système considéré. Ma remarque initiale sur la gestion des IPP n'est donc plus vraiment valide.
 
- Si un système souhaite répertorier les différents identifiants locaux (Les IPP de plusieurs établissements par exemple), il pourrait être intéressant d'ajouter un slice supplémentaire au profil, "XPI" par exemple pour "External patient Identifier". Le CodeSystem fr-v2-0203 contient la valeur EXTRN (Identifiant externe) qui pourrait à mon sens répondre au besoin.
 
- Pour les slices "RRI" et "NDP" en revanche, il parait possible pour des Repository à échelle nationale par exemple, d'avoir plusieurs occurrences de ce Slice afin de répertorier tous les identifiants régionaux (discriminés par le champs "system" mais possédant le même "type").
 
- Enfin en discutant sur ce sujet j'ai remarqué que les valeurs "RI" et "RRI" n'appartiennent pas au CodeSystem fr-v2-0203
C'est pourtant ce code system qui apparait dans les slices PI et RRI du profil Patient:
{
  "coding": [
    {
      "system": "http://interopsante.org/CodeSystem/fr-v2-0203",
      "code": "PI",
      "display": "Patient internal identifier"
    }
  ]
}
 
Cordialement,

**Comment by nriss** [comment]
PI et RRI appartiennent bien au system http://terminology.hl7.org/CodeSystem/v2-0203 qui est proposé dans le binding d'Identifier.

<img width="738" alt="image" src="https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/48218773/d5f2060c-de63-4f00-b8f0-07e0090f4881">

<img width="903" alt="image" src="https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/48218773/e25fa5f2-7711-4356-824c-1f18e16c11ca">


Je vois que dans l'ancienne version de FrPatient sur simplifier, le system interopsanté était utilisé alors que c'est un code qui est dans le system international.

Cf : https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783568
<img width="1225" alt="image" src="https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/48218773/a89efd3c-bd58-4d9d-8724-f5a2bd863022">

Je viens de voir que ce ValueSet est bien défini dans FrCore : https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/ValueSet-fr-core-identifier-type-v1-0.html
Mais celui-ci n'est pas bindé à Patient.identifier.type

J'ai l'impression que l'on est presque bon, il faut juste que l'on mette le binding de Patient.identifier.type à https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/ValueSet-fr-core-identifier-type-v1-0.html, est-ce qu'on serait bon selon toi ?

**Comment by alexgrosbois** [comment]
Bonjour Nicolas, et merci pour ta réponse.

Effectivement mes remarques portaient sur le profile FrPatient sur Simplifier.
Je viens de regarder sur la v2.0.0 et voici mes remarques:

- Tout à fait d'accord avec ce nouveau binding Patient.identifier.type avec le ValueSet https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/ValueSet-fr-core-identifier-type-v1-0.html  qui contient tous les codes utilisés dans les définitions des slices

- Par contre il manque dans cette nouvelle version du profil les slices INS-NIR et INS-NIA qui me semblent particulièrement utiles.

- Reste tout de même la question des cardinalités qui ne sont pas modifiées dans la nouvelle version du FrPatient. Je ne suis pas certain que mes propositions ci-dessus soient les plus pertinentes (RRI et NDP avec cardinalités 0..*, et éventuellement une slice supplémentaire pour un External Patient ID à 0..* aussi), 

![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/133106181/ee1f5d08-e7b8-4d33-879d-4492c20b1ab4)

- Dans le cas où il y aurait un slice XPI (External PI) ajouté, il faudrait aussi ajouter le code EXTRN (Identifiant externe) dans le ValueSet.

**Comment by nriss** [comment]
Pour résumer :

- [ ] Vérifier les cardinalités des slices Patient.identifier (j'avoue ne pas avoir les idées au clair sur ce qu'il faut, peut être attendre un GT et une prochaine release pour éclairer ce point)
- [ ] Etudier pourquoi est-ce que l'on a supprimé les slices INS-NIR / INS-NIA : est-ce que vous avez une idée @ypoiron @isa-ans ?
- [ ] Rajouter le binding de Patient.identifier.type au ValueSet défini ici :  https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/ValueSet-fr-core-identifier-type-v1-0.html 
- [ ] Etudier le rajout d'une slice XPI (External PI) et rajouter le code EXTRN au ValueSet  https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/ValueSet-fr-core-identifier-type-v1-0.html

**Comment by nriss** [comment]
- [ ] INS NIR et NIA ont été reportés sur le profil patient INS Qualifié, car seul le patient qualifié peut avoir un NIR et NIA. Nous allons expliciter ça dans le guide d'implémentation (cf https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/StructureDefinition-fr-core-patient-ins.html)
- [ ] Changer le short de l'identifier 

<img width="857" alt="image" src="https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/48218773/510e01c9-1ab5-4f7e-80f9-3c44376a2dfd">

- [ ] Nous n'allons pas rajouter de slice XPI, mais le slicing d'identifier est open donc aucun problème pour rajouter d'autres identifier non définis par les slices.

- [ ] NDP : Il n'y a qu'un NDP par patient à notre connaissance : pourquoi est-ce qu'il pourrait y en avoir plusieurs selon toi ?

- [ ] Identifiant régional : ok pour relaxer à 0..*, chaque région devra définir son system (à rajouter dans le short)

**Comment by alexgrosbois** [comment]
Bonjour Nicolas,

Je ne suis pas du tout expert sur le NDP mais j'avais lu quelque part que le NDP pouvait varier avec un changement de Carte Vitale, car il contient le numéro de série de la CV.

Je viens de retrouver cette info sur ces sites, mais l'info date un peu donc je ne sais pas si c'est toujours valide:

![image](https://github.com/Interop-Sante/hl7.fhir.fr.core/assets/133106181/fc3c75e8-4473-4b1e-90be-14516190219c)

sources:
- https://www.legifrance.gouv.fr/cnil/id/CNILTEXT000020022185/
- https://www.techno-science.net/glossaire-definition/Carte-Vitale-page-4.html
