### ISSUE TITLE
Gestion des profils sur la ressource Patient

### ISSUE THREAD

**Issue by GCHASTIN** [Interop-Sante/hl7.fhir.fr.core#98]
J'ai remarqué qu'il existait désormais 2 profils pour la ressource Patient. 
- https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-patient-ins
- https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-patient

Je me pose plusieurs questions.

Qu'est il envisager pour lier 2 ressources (1 au profil **fr-core-patient** et une au profil **fr-core-patient-ins**) qui correspondraient à un même patient?

J'imagine les solutions suivantes : 

- Je pense que la ressource **fr-core-patient** sera la plus part du temps créée avant **fr-core-patient-ins**. La ressource **fr-core-patient-ins** pourrait elle venir écraser la première pour ne conserver qu'une seule ressource, en récupérant les informations qui ne seraient pas contenue dans la seconde?

- L'utilisation de l'élément **link** permettrait de lier les ressources. Est ce la solution envisagée (la plus probable à mon sens)?

Remarque ; Le fait d'avoir 2 ressources pour un même patient va dupliquer l'information (birthPlace, birthDate, gender). L'extension identityReliability est présente dans les 2 profils. Pourquoi puisque le profil dédié à l'INS existe? L'extension **birth-list-given-name** pourrait être appliquée au profil **fr-core-patient**.

Pourquoi avez opté pour la création d'un profil propre à l'INS?

**Comment by nriss** [comment]
Bonjour ! Nous avons créé ce profil qui hérite du profil Patient pour indiquer les contraintes d'un profil patient validé.

A mon sens, il n'est pas nécessaire d'avoir deux ressources pour un même patient : étant donné que le patient ins hérite du fr-patient, si une instance est compatible avec le patient INS, elle le sera également avec le fr.core.patient

Ainsi, certaines ressources vont avoir dans meta.profile uniquement le profil fr-core-patient (et sont conformes qu'à celles ci), d'autres pourront être conformes aux deux (fr-core-patient + fr-core-patient-ins)

Après il faudrait discuter du cas d'usage pour voir pourquoi on aurait besoin de deux instances et de l'usage de link, là il s'agit de profils génériques

**Comment by nriss** [comment]
Pour compléter :
- Concernant l'extension birth-list-given-name, ça me choquerait pas de la mettre au niveau du fr-core-patient en optionnel et de la rendre obligatoire au niveau du patient INS
- Voir même rajouter l'extension au profil FrHumanName ?

Peut être que @ypoiron @isa-ans vous avez une idée ayant travaillé sur PAM

**Comment by GCHASTIN** [comment]
Merci Nicolas pour ces retours.
